### ISSUE TITLE
Hexo 3.2 Roadmap

### ISSUE THREAD

**Issue by tommy351** [hexojs/hexo#1330]
- [x] Include/Exclude source files
- [x] Not to delete other non-hexo files during generation. #1310 
- [ ] Get rid of `index.html`. #1306
- [x] Ignore `node_modules` folder in the theme. #1316
- [ ] Make anchors in each posts unique. #1302 
- [ ] Expose code highlight point. #1300 
- [ ] Inline CSS helper. #1295 
- [x] Detect the current category/tag in `is_category/tag` helper. #1278 

I'll start working on this during summer vacation. Feel free to write your suggestions below.

**Comment by Xuanwo** [comment]
Sounds great!

**Comment by Xuanwo** [comment]
`Include/Exclude source files`

I think we can make it a default option, almost everyone want their md files to be saved.
We can create a `source` branch and upload the source files while we deploy.

**Comment by tommy351** [comment]
@Xuanwo Yep, `.htaccess` for example.

**Comment by Xuanwo** [comment]
关于插件的更新，我还有一个问题是这样的。

我一直在用travis部署，然后重装系统之后也一直没有重新安装nodejs环境，所以我没有运行`npm update`的环境，导致我的package.json中插件的有关信息一直没有得到更新。这个问题导致我有一段时间一直build failed。
有没有办法始终保持自己安装的各项插件始终最新呢？

**Comment by tommy351** [comment]
You can use `npm outdated` command to check what packages need to be updated.

**Comment by Xuanwo** [comment]
I got it.

然后我还有的问题就是像这样：https://github.com/hexojs/hexo/issues/1333
对这种不需要渲染的东西，有没有更加机智地处理办法，感觉skip_render并不是十分好用。
可以另外建立一个raw文件夹，然后generate之后copy到public中去。

**Comment by jr0cket** [comment]
Generating an RSS feed for a specific tag (categories are too broad)
- my blog covers many topics and so its not possible to share my feed with many specific blog rollers.  This reduces the exposure my blog gets :(

Defining top level navigation, disqus name, banner logo, etc into the main _config.yml file rather than the theme, (or allowing it to be passed through).  This would reduce the need to also put the theme into version control

**Comment by borian** [comment]
Nice, I have been waiting for `.htaccess` support !  :thumbsup:

**Comment by Djabx** [comment]
I agree with @jr0cket 
I would love to not put the theme into version control (at least not with my blog).

Maybe reference themes as an npm plugin / git submodule ? 
But the question of the configuration file pop-up...

**Comment by leesei** [comment]
I also agree on have a root config (say `theme.yaml`) to override theme config (something like `extend(theme/config.yaml, ./theme.yaml)`.
Most user just pull the theme and modify the config once and for all. It's quite troublesome to fork and check in the theme just for the updated yaml.

**Comment by Xuanwo** [comment]
Agree with @leesei, maybe we can have a default setting and a user setting. And user setting will override default setting.

**Comment by diessica** [comment]
Happy that the issue I reported was noticed. I'll stick around :)

**Comment by OdinsHat** [comment]
* Not just .htaccess but CNAME file which is required for hosting on Github.

**Comment by emceeaich** [comment]
:+1: to @jr0cket's request to move user configurations out of the theme and up to the site level.

This would require modifications to existing themes, but we could split up the work with theme creators/maintainers.

**Comment by emceeaich** [comment]
I would like to have https://www.npmjs.com/package/hexo-generator-feed in the initial install and the configuration block for syndication feeds by default.

**Comment by Xuanwo** [comment]
ref https://github.com/hexojs/hexo/issues/1626

How about a feature that achieve the arrticles in other floder instead of `_post` ?

**Comment by Vinnl** [comment]
I don't really like +1 comments, but there doesn't seem to be another way to indicate demand, so... Per-tag RSS feeds would be great. Second to that overriding theme settings would be nice as well.

(Also, thanks! Hexo seems to be pretty much everything I was looking for!)

**Comment by Xuanwo** [comment]
@tommy351 although `Include/Exclude source files` func added, but due to this comment : https://github.com/hexojs/hexo/issues/1705#issuecomment-170577705 , maybe we should copy them to `public` instead of just excloud them.

**Comment by akfish** [comment]
How about #1780

**Comment by soulteary** [comment]
@Xuanwo ，skip files的需求我也遇到了...感觉可以考虑让用户自己挂脚本到render里，做路径排除，以及排除后的操作，是sync，还是怎么样，实际修改成本，应该只有在plugin/generate＊里添加一个hook name...

实现参考：https://github.com/soulteary/hexo-extend-plugin/blob/master/patch/hexo/lib/plugins/generator/page.js

**Comment by soulteary** [comment]
另外，何不让用户自己选择开启或者关闭一些features呢，搭配自带的cli使用，包括并不限rss之类的。

实现参考：https://github.com/soulteary/hexo-extend-plugin/tree/master/patch/hexo/lib/plugins/console

**Comment by NoahDragon** [comment]
Moved to road map 4.0
