### ISSUE TITLE
Hexo 4.0 Roadmap

### ISSUE THREAD

**Issue by NoahDragon** [hexojs/hexo#2492]
Here is a list for Hexo 4.0 roadmap:

- [ ] Convert old js code to ES6 standard.
- [ ] Speed is the key. 
- [ ] Expand the cli tool.
- [ ] Reduce the number of issues to below 100, which is a decent amount to manage by few people.
- [ ] Raise fund to cover existing fees (like domain name fee) and buy extra services (like NPM organization).
- [ ] Clean up left over tasks in old milestone

Please feel free to leave your thought in comments.

**Comment by kirkcameron** [comment]
make sure, that hexo s and hexo g are in sync, before introducing any new features, please.

https://github.com/hexojs/hexo/issues/2503

**Comment by mnlbox** [comment]
Please work on performance and multi core support on `hexo server` and `hexo generate`. I have major problem with big site generation in Hexo like this: #2579

**Comment by NoahDragon** [comment]
@mnlbox Yes, it will be the major update in 4.0 build.

**Comment by kirkcameron** [comment]
any news, regarding the release date, especially for https://github.com/hexojs/hexo/issues/2503 ?

**Comment by NoahDragon** [comment]
@kirkcameron Not yet. The server calls the `render` function is as same as the generator, don't have clue why causes the differences.

**Comment by huiwang** [comment]
@NoahDragon could you please share more details on the performance improvement?

**Comment by NoahDragon** [comment]
@huiwang Thanks for asking. 

The generating performance issue is really hard to reproduce. It may cause by plugin, renderer, or Hexo self. We occasionally receive issue regarding performance, but only few shared their source to investigate. As far as I know, all of them are plugin and theme issue. 

I also tested performance on Hexo vanilla install, 1000 posts generated costs 3 mins. Still, have space to improve, but seems not a major issue.

**Comment by tcrowe** [comment]
I noticed there's some confusion about how to do unit testing. This `mocha.opts` will help:
https://gist.github.com/tcrowe/b22a63daea19eaee69fe2bc37adee854

**Comment by tcrowe** [comment]
[Prettier](https://prettier.io) can be included to force a uniform style across all hexo projects and it will integrate with [eslint-config-hexo](https://github.com/hexojs/eslint-config-hexo).

`npm install prettier eslint-plugin-prettier

`./.pretterrc`

```json
{
  "proseWrap": "never"
}
```

`./.eslintrc`

```json
"plugins": ["node", "prettier"],
```

`eslint --fix` will then format using prettier.

**Comment by SukkaW** [comment]
I think Hexo needn't remove highlight.js as it doesn't affect performance.
.
https://github.com/hexojs/hexo/issues/1036#issuecomment-433833882

**Comment by microSoftware** [comment]
Is Hexo still maintained? I love it but most packages are years old and I can't make my website multi-language :(

**Comment by YoshinoriN** [comment]
@microSoftware 

> Is Hexo still maintained?

Yes. Sure :)

> most packages are years old

As you know some packages are not published new version but we continue to commit each [official repositories](https://github.com/hexojs).

> I can't make my website multi-language :(

Hexo i18n [seems a little bit difficult](https://github.com/hexojs/hexo/labels/i18n). (Sorry, I'm not familiar with Hexo i18n...)
I think [this issue](https://github.com/hexojs/hexo/issues/3247) @tcrowe answer might help you :)

**Comment by microSoftware** [comment]
Ok. After I tried most things to make it multi-language. I think the easiest solution is to create a seperate blog for each language. And create a simple dropdown in javascript in the theme.

**Comment by DBJDBJ** [comment]
@microSoftware ,  yes that is the most feasible way. Anything else requires Concept, Architecture, Design and Implementation that will complicate the things considerably. Just to be used by very small percentage of users.

If still interested, there is no shame in learning from (very long)WP experience, Perhaps starting [from here.](https://colorlib.com/wp/wordpress-multilingual-plugins/)

**Comment by gautamz07** [comment]
@tcrowe is there a specific brance all these changes are being developed or worked on ?

**Comment by tcrowe** [comment]
@gautamz07 Each change, or set of changes, will be done in individual issues and PRs. So, if you want to do one of the items in the [original post](https://github.com/hexojs/hexo/issues/2492#issue-219942601) you can create a branch on your computer, do the change, and then create a PR.

Some patience is required to get a review and approval.

**Comment by YoshinoriN** [comment]
I changed issue title. Please see #3598 discussion.

**Comment by noraj** [comment]
#3259 seems to bring breaking changes

**Comment by BRAVO68WEB** [comment]
I have created a New Hexo Theme 

[GitHub Repo](https://github.com/BRAVO68WEB/hexo-webnary-theme/)

[Demo URL](https://webnary.netlify.app/)

**Comment by stevenjoezhang** [comment]
@BRAVO68WEB You can submit your theme here: https://github.com/hexojs/site/pulls

**Comment by mahnunchik** [comment]
Is this project dead?

**Comment by SukkaW** [comment]
Drops `resolve` from dependency in Hexo 7.0.0, see https://github.com/hexojs/hexo/pull/4863

**Comment by yaoqs** [comment]
wish add new command, such as:
```
hexo delete my_post //delete post
hexo modify my_post //modify post,if not exist, new one
```

**Comment by awongCM** [comment]
Hi there,

Are you still looking for more active contributors for this page? Just curious..

**Comment by sonnystark** [comment]
Hey all! 
Just out of curiosity, is Hexo still under development or what is the status?

**Comment by stevenjoezhang** [comment]
@sonnystark Hi! Yes, Hexo is still actively maintained.

The latest stable release is [v8.1.2](https://github.com/hexojs/hexo/releases/tag/v8.1.2), released in May 2026, and development on `master` is ongoing. We have also recently merged several performance improvements and bug fixes.

This roadmap issue was opened in 2017, so its checklist no longer fully reflects the project’s current priorities. (We only update some important feature requests in the roadmap). Individual features and fixes are tracked through their own issues and pull requests. You can follow the latest activity through our [releases](https://github.com/hexojs/hexo/releases) and [recent commits](https://github.com/hexojs/hexo/commits/master/).

Contributions are always welcome. Thanks for checking in!

**Comment by sonnystark** [comment]
@stevenjoezhang Hey! Thank you for your reply. That's great to hear. I have been using Hexo in a few private projects lately and really like it. I know you mentioned that the roadmap checklist is not up to date but I noticed that there at one point was an interest in a newsletter. Is that still something that is desired? I would definitely be up for working on that, if that is the case.

Thanks in advance and have a great weekend!

**Comment by stevenjoezhang** [comment]
@sonnystark Thanks for offering to help!

We currently publish project updates on [hexo.io/news](https://hexo.io/news/) and through social media channels. However, we do not yet provide other formats, such as an email newsletter or mailing list.

Most of our current updates also focus on Hexo itself and plugins maintained by the Hexo team (e.g. https://github.com/hexojs/site/pull/2446).

If you have any ideas about the Hexo newsletter, please feel free to share your thoughts. Thanks again for your interest!
