### ISSUE TITLE
post的keywords: xx 生成的是<meta property="article:tag" content="xx">而不是keywords

### ISSUE THREAD

**Issue by 799953468** [hexojs/hexo#4101]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## How to reproduce?

* Step1
* Step2
* etc...

## Environment & Settings

**Node.js & npm version**

```
Node.js v13.4.0
npm v6.13.6
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
+-- @1v9/hexo-next-nightmode@1.1.2 (github:1v9/hexo-next-nightmode#d32e7b61c303c8e73aaf51dd46e0b0381080de67)
+-- babel-runtime@6.26.0
+-- bluebird@3.7.2
+-- canvas-nest.js@2.0.4
+-- core-js@3.6.4
+-- extend@3.0.2
+-- hexo@4.2.0
+-- hexo-abbrlink@2.0.5
+-- hexo-deployer-git@2.1.0
+-- hexo-filter-optimize@0.3.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-calendar@0.0.1 (github:theme-next/theme-next-calendar#4de1d42ae3fff83a1aaae5d4f01ffc29444e4222)
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-searchdb@1.2.0
+-- hexo-generator-sitemap@2.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-leancloud-counter-security@1.4.1
+-- hexo-next-title@0.1.0 (github:theme-next/hexo-next-title#d24494b244a637919053e845e31f7a787556de04)
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- hexo-symbols-count-time@0.7.0
+-- lodash@4.17.15
+-- lodash.template@4.5.0
+-- minimatch@3.0.4
+-- mixin-deep@2.0.1
`-- set-value@3.0.1
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "@1v9/hexo-next-nightmode": "github:1v9/hexo-next-nightmode",
    "babel-runtime": "^6.26.0",
    "bluebird": "^3.7.2",
    "canvas-nest.js": "^2.0.4",
    "core-js": "^3.6.4",
    "extend": "^3.0.2",
    "hexo": "^4.2.0",
    "hexo-abbrlink": "^2.0.5",
    "hexo-deployer-git": "^2.1.0",
    "hexo-filter-optimize": "^0.3.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-calendar": "github:theme-next/theme-next-calendar",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-searchdb": "^1.2.0",
    "hexo-generator-sitemap": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-leancloud-counter-security": "^1.4.1",
    "hexo-next-title": "github:theme-next/hexo-next-title",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-symbols-count-time": "^0.7.0",
    "lodash": "^4.17.15",
    "lodash.template": "^4.5.0",
    "minimatch": "^3.0.4",
    "mixin-deep": "^2.0.1",
    "set-value": "^3.0.1"
  }
}

```

**Comment by SukkaW** [comment]
https://github.com/hexojs/hexo/issues/4072
