### ISSUE TITLE
Hexo on exit event not triggered after all hexo process finished (onExit)

### ISSUE THREAD

**Issue by dimaslanjaka** [hexojs/hexo#4822]
Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Environment & Settings
- Node 14.18.1
- NPM 8.1.3
- hexo 5.4.0

# Behavior
I just testing function to be executed before hexo exit, but **why the function triggered before all events completed** ?

**todo:** 
manipulate the html code using JSDOM, then cache it so as not to process the same (duplicate) html string. then save it in file as cache before hexo exit (on exit) and restore that cache to object when hexo ready (on ready).
the manipulation process will be repeated if the page content changes (updated or edited), otherwise it will be returned according to the stored cache.
cache will be cleared when triggered by `hexo clean`.
in my case testing hexo event, i want to:
- saving object cache to file before hexo exit `hexo.on('exit')`
- restore object cache from file after hexo ready `hexo.on('ready')`

## This is from my own plugin
```js
// packages/hexo-seo/src/index.ts
hexo.on("exit", () => {
  console.log("Scheduling functions on process exit");
});
```
## Others
![image](https://user-images.githubusercontent.com/12471057/142859597-25d1756f-b37d-43e5-aac5-5990fe67deb1.png)

**Comment by stevenjoezhang** [comment]
These event callback functions are non-blocking. You will need to use some other methods to achieve this, such as registering filters.

**Comment by dimaslanjaka** [comment]
> These event callback functions are non-blocking. You will need to use some other methods to achieve this, such as registering filters.

such like registering function on process exit ?
